/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     13/09/2021 16:38:28
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "stm32f1xx_hal.h"
#include "StateMachine_lib/inc/Action/Action.h"

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
}
